"""Small, shared V0 configuration.

Keep this file boring: these are research inputs, not a future taxonomy service.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUTPUTS = ROOT / "outputs" / "runs"
ENTITIES = ROOT / "outputs" / "entities"
REDDIT_CONTENT_INDEX = ROOT / "outputs" / "reddit_content_index.json"
REFRESH_WINDOWS_DAYS = {"trend": 7, "discovery": 30}
REFRESH_MODES = ("trend", "discovery", "backfill")
RESEARCH_WINDOW_DAYS = 30
INSTAGRAM_RESULTS_LIMIT = 100
INSTAGRAM_PROFILE_BATCH_SIZE = 25
YOUTUBE_RESULTS_LIMIT = 100
YOUTUBE_CHANNEL_BATCH_SIZE = 25
YOUTUBE_RECENT_VIDEOS = 30
REDDIT_RESULTS_PER_QUERY = 25
REDDIT_BATCH_SIZE = 50
PROMPTS = ROOT / "prompts"

DEFAULT_SOURCES = ("instagram", "youtube", "web")
OPTIONAL_SOURCES = ("reddit", "x")
LOCATION_SCOPES = ("All India", "Zone", "State", "City")
INDIAN_ZONES = ("North", "South", "East", "West", "Central", "Northeast", "Other")
INDIAN_STATES = (
    "Andhra Pradesh", "Assam", "Bihar", "Chhattisgarh", "Delhi", "Goa",
    "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka",
    "Kerala", "Madhya Pradesh", "Maharashtra", "Odisha", "Punjab",
    "Rajasthan", "Tamil Nadu", "Telangana", "Uttar Pradesh", "Uttarakhand",
    "West Bengal", "Other",
)

ARTIST_LANGUAGES = (
    "All languages",
    "Hindi", "Tamil", "Telugu", "Malayalam", "Kannada", "Bengali",
    "Marathi", "Punjabi", "Gujarati", "English", "Other",
)

ACTOR_LANGUAGES = (
    "Hindi", "English", "Tamil", "Telugu", "Malayalam", "Kannada",
    "Bengali", "Marathi", "Korean", "Japanese", "Spanish", "French", "Other",
)

ACTOR_MARKETS = (
    "India", "United States", "United Kingdom", "South Korea", "Japan",
    "China", "Spain", "France", "Europe", "Global", "Other",
)

ACTOR_INDUSTRIES = (
    "Bollywood",
    "Tollywood (Telugu cinema)",
    "Kollywood (Tamil cinema)",
    "Mollywood (Malayalam cinema)",
    "Sandalwood (Kannada cinema)",
    "Pollywood (Punjabi cinema)",
    "Marathi cinema",
    "Bengali cinema",
    "Gujarati cinema",
    "Bhojpuri cinema",
    "Hollywood",
    "British cinema",
    "Korean cinema",
    "Japanese cinema",
    "Chinese cinema",
    "Spanish cinema",
    "French cinema",
    "Other",
)

ACTOR_INDUSTRIES_BY_LANGUAGE = {
    "Hindi": ("Bollywood",),
    "English": ("Hollywood", "British cinema"),
    "Tamil": ("Kollywood (Tamil cinema)",),
    "Telugu": ("Tollywood (Telugu cinema)",),
    "Malayalam": ("Mollywood (Malayalam cinema)",),
    "Kannada": ("Sandalwood (Kannada cinema)",),
    "Bengali": ("Bengali cinema",),
    "Marathi": ("Marathi cinema",),
    "Punjabi": ("Pollywood (Punjabi cinema)",),
    "Gujarati": ("Gujarati cinema",),
    "Korean": ("Korean cinema",),
    "Japanese": ("Japanese cinema",),
    "Spanish": ("Spanish cinema",),
    "French": ("French cinema",),
    "Other": ("Other",),
}

ACTOR_MARKETS_BY_INDUSTRY = {
    "Bollywood": ("India", "Global"),
    "Tollywood (Telugu cinema)": ("India", "Global"),
    "Kollywood (Tamil cinema)": ("India", "Global"),
    "Mollywood (Malayalam cinema)": ("India", "Global"),
    "Sandalwood (Kannada cinema)": ("India", "Global"),
    "Pollywood (Punjabi cinema)": ("India", "Global"),
    "Marathi cinema": ("India", "Global"),
    "Bengali cinema": ("India", "Global"),
    "Gujarati cinema": ("India", "Global"),
    "Bhojpuri cinema": ("India", "Global"),
    "Hollywood": ("United States", "Global"),
    "British cinema": ("United Kingdom", "Global"),
    "Korean cinema": ("South Korea", "Global"),
    "Japanese cinema": ("Japan", "Global"),
    "Chinese cinema": ("China", "Global"),
    "Spanish cinema": ("Spain", "Europe", "Global"),
    "French cinema": ("France", "Europe", "Global"),
    "Other": ("Global", "Other"),
}

INDIAN_CITIES = (
    "Mumbai", "Delhi NCR", "Bengaluru", "Hyderabad", "Chennai", "Kolkata",
    "Pune", "Ahmedabad", "Jaipur", "Chandigarh", "Kochi", "Lucknow",
    "Indore", "Other",
)

ARTIST_L2_TAGS = {
    "Celebrity Appearance": ("Film Stars", "Pageant Winner", "Sports Celebrities", "TV Personalities"),
    "Anchor / Emcee": ("Anchor", "Emcee", "Pageant Winner", "Radio Jockey", "TV Personalities", "Voice Over Artist"),
    "Dancer / Troupe": ("Belly Dancers", "Bhangra", "Bollywood", "Choreographers", "Exotic Dancers", "Folk", "Indian Classical", "Kids Troupe", "Reality Show Dancers", "Religious", "Western"),
    "Comedian": ("Impersonators", "Mimicry", "Reality Show Comedians", "Stand Up"),
    "DJ": ("Bass", "Bollywood", "Deep House", "Dubstep", "EDM", "Electro", "Fusion", "Indie", "Minimal", "Pop", "Progressive", "Psychedelic", "Rock", "Sufi", "Techno", "Trance", "Trap", "Virtual DJ"),
    "Live Band": ("Alternative", "Blues", "Bollywood", "Electronica", "Folk", "Funk", "Fusion", "Hip Hop", "Indie", "Jazz", "Metal", "Orchestra", "Pop", "Progressive", "Psychedelic", "Punk", "Rap", "Reggae", "Rock", "Rock N Roll", "Sufi", "Tribute"),
    "Instrumentalist": ("Flutist", "Folk", "Fusion", "Guitarist", "Indian Classical Instruments", "Keyboardist", "One-Man Band", "Percussionist", "Pianist", "Saxophonist", "Violinist"),
    "Magician": ("Close Up Magicians", "Hypnotist", "Illusionist", "Stage Magicians"),
    "Make-up Artist / Stylist": ("Bridal & Parties", "Fashion", "Fashion Choreographer", "Film & Television", "Wardrobe Stylist"),
    "Singer": ("Acoustic Singer", "Bhajan", "Bollywood", "Classical", "English Retro", "Ghazal", "Hindi Retro", "Indian Classical", "Indian Folk", "Jagran", "Karaoke", "Qawwali", "Rapper", "Religious"),
    "Speaker": ("Film Stars", "Life Coach", "Motivational", "Spiritual", "Training", "Vocational"),
    "Photo / Videographer": ("Baby", "Candid", "Concept", "Corporate Films", "Documentary Films", "Events", "Fashion", "Portfolio", "Portrait", "Product", "Short Films", "Weddings"),
    "Variety Artist": ("Acrobat Artists", "Balloon Artists", "Bartenders", "Beatboxer", "Caricaturists", "Fire Artists", "Jugglers", "Mehendi Artists", "Painters", "Promoters", "Puppeteers", "Sand Artists", "Shadow Artists", "Stage Magicians", "Stunt Artists"),
    "Influencer": ("Auto & Tech", "Beauty & Wellness", "Comedy & Humor", "Education & Learning", "Faith & Spirituality", "Fashion & Lifestyle", "Finance & Business", "Fitness & Health", "Food & Culinary", "Gaming & Esport", "News & Politics", "Pet & Animal Care", "Travel & Adventure"),
    "Model": ("Art Models", "Catalogue Models", "Commercial Models", "Foreign Models", "Glamour Models", "International Models", "Promotional Models", "Runway Models"),
}

ARTIST_CATEGORIES = tuple(ARTIST_L2_TAGS) + ("Other",)
ARTIST_GENRES = tuple(sorted({tag for tags in ARTIST_L2_TAGS.values() for tag in tags})) + ("Other",)

ARTIST_L1_HASHTAGS = {
    "Celebrity Appearance": ("celebrityappearance", "celebritybooking", "indiancelebrity"),
    "Anchor / Emcee": ("indiananchor", "emceeindia", "eventhostindia"),
    "Dancer / Troupe": ("indiandancer", "dancetroupeindia", "dancebooking"),
    "Comedian": ("indiancomedian", "standupcomedyindia", "comedybooking"),
    "DJ": ("indiandj", "djbooking", "indianmusic"),
    "Live Band": ("indianliveband", "livebandindia", "bandbooking"),
    "Instrumentalist": ("indianmusician", "instrumentalistindia", "musicbooking"),
    "Magician": ("indianmagician", "magicshowindia", "magicianbooking"),
    "Make-up Artist / Stylist": ("indianmakeupartist", "indianstylist", "makeupartistbooking"),
    "Singer": ("indiansinger", "indianmusic", "livemusicindia", "singerbooking"),
    "Speaker": ("indianspeaker", "motivationalspeaker", "speakerbooking"),
    "Photo / Videographer": ("indianphotographer", "indianvideographer", "photographybooking"),
    "Variety Artist": ("indianvarietyartist", "eventartistsindia", "varietyartistbooking"),
    "Influencer": ("indianinfluencer", "indiancontentcreator", "influencerbooking"),
    "Model": ("indianmodel", "indianfashionmodel", "modelbooking"),
}

# Focused Instagram hashtags keyed by (L1 category, L2 genre).
# Keep this as the final lookup table; the collector should not need to know
# how a hashtag was derived.
ARTIST_L2_HASHTAGS = {
 ('Celebrity Appearance', 'Film Stars'): ('filmstars',
                                          'indianfilmstars',
                                          'filmstarsbooking',
                                          'appearanceindia',
                                          'celebritybooking'),
 ('Celebrity Appearance', 'Pageant Winner'): ('pageantwinner',
                                              'indianpageantwinner',
                                              'pageantwinnerbooking',
                                              'appearanceindia',
                                              'celebritybooking'),
 ('Celebrity Appearance', 'Sports Celebrities'): ('sportscelebrities',
                                                  'indiansportscelebrities',
                                                  'sportscelebritiesbooking',
                                                  'appearanceindia',
                                                  'celebritybooking'),
 ('Celebrity Appearance', 'TV Personalities'): ('tvpersonalities',
                                                'indiantvpersonalities',
                                                'tvpersonalitiesbooking',
                                                'appearanceindia',
                                                'celebritybooking'),
 ('Anchor / Emcee', 'Anchor'): ('anchor',
                                'indiananchor',
                                'anchorbooking',
                                'eventhostindia',
                                'emceeindia',
                                'hostbooking'),
 ('Anchor / Emcee', 'Emcee'): ('emcee',
                               'indianemcee',
                               'emceebooking',
                               'eventhostindia',
                               'emceeindia',
                               'hostbooking'),
 ('Anchor / Emcee', 'Pageant Winner'): ('pageantwinner',
                                        'indianpageantwinner',
                                        'pageantwinnerbooking',
                                        'eventhostindia',
                                        'emceeindia',
                                        'hostbooking'),
 ('Anchor / Emcee', 'Radio Jockey'): ('radiojockey',
                                      'indianradiojockey',
                                      'radiojockeybooking',
                                      'eventhostindia',
                                      'emceeindia',
                                      'hostbooking'),
 ('Anchor / Emcee', 'TV Personalities'): ('tvpersonalities',
                                          'indiantvpersonalities',
                                          'tvpersonalitiesbooking',
                                          'eventhostindia',
                                          'emceeindia',
                                          'hostbooking'),
 ('Anchor / Emcee', 'Voice Over Artist'): ('voiceoverartist',
                                           'indianvoiceoverartist',
                                           'voiceoverartistbooking',
                                           'eventhostindia',
                                           'emceeindia',
                                           'hostbooking'),
 ('Dancer / Troupe', 'Belly Dancers'): ('bellydancers',
                                        'indianbellydancers',
                                        'bellydancersbooking',
                                        'bellydanceindia',
                                        'bellydancerindia',
                                        'bellydancebooking',
                                        'danceindia',
                                        'dancetroupeindia',
                                        'dancebooking'),
 ('Dancer / Troupe', 'Bhangra'): ('bhangradancer',
                                  'bhangraindia',
                                  'bhangraartist',
                                  'danceindia',
                                  'dancetroupeindia',
                                  'dancebooking'),
 ('Dancer / Troupe', 'Bollywood'): ('bollywoodsinger',
                                    'bollywoodmusic',
                                    'bollywoodlive',
                                    'bollywoodartist',
                                    'danceindia',
                                    'dancetroupeindia',
                                    'dancebooking'),
 ('Dancer / Troupe', 'Choreographers'): ('choreographers',
                                         'indianchoreographers',
                                         'choreographersbooking',
                                         'choreographerindia',
                                         'dancechoreographer',
                                         'choreographybooking',
                                         'danceindia',
                                         'dancetroupeindia',
                                         'dancebooking'),
 ('Dancer / Troupe', 'Exotic Dancers'): ('exoticdancers',
                                         'indianexoticdancers',
                                         'exoticdancersbooking',
                                         'danceindia',
                                         'dancetroupeindia',
                                         'dancebooking'),
 ('Dancer / Troupe', 'Folk'): ('folk',
                               'indianfolk',
                               'folkbooking',
                               'danceindia',
                               'dancetroupeindia',
                               'dancebooking'),
 ('Dancer / Troupe', 'Indian Classical'): ('indianclassicalmusic',
                                           'classicalsinger',
                                           'classicalmusicindia',
                                           'indianclassicalartist',
                                           'danceindia',
                                           'dancetroupeindia',
                                           'dancebooking'),
 ('Dancer / Troupe', 'Kids Troupe'): ('kidstroupe',
                                      'indiankidstroupe',
                                      'kidstroupebooking',
                                      'kidstroupeindia',
                                      'kidseventindia',
                                      'danceindia',
                                      'dancetroupeindia',
                                      'dancebooking'),
 ('Dancer / Troupe', 'Reality Show Dancers'): ('realityshowdancers',
                                               'indianrealityshowdancers',
                                               'realityshowdancersbooking',
                                               'danceindia',
                                               'dancetroupeindia',
                                               'dancebooking'),
 ('Dancer / Troupe', 'Religious'): ('religious',
                                    'indianreligious',
                                    'religiousbooking',
                                    'devotionalmusicindia',
                                    'devotionalsinger',
                                    'bhajanartist',
                                    'danceindia',
                                    'dancetroupeindia',
                                    'dancebooking'),
 ('Dancer / Troupe', 'Western'): ('westernmusicindia',
                                  'westernsingerindia',
                                  'danceindia',
                                  'dancetroupeindia',
                                  'dancebooking'),
 ('Comedian', 'Impersonators'): ('impersonators',
                                 'indianimpersonators',
                                 'impersonatorsbooking',
                                 'comedyindia',
                                 'standupindia',
                                 'comedybooking'),
 ('Comedian', 'Mimicry'): ('mimicry',
                           'indianmimicry',
                           'mimicrybooking',
                           'comedyindia',
                           'standupindia',
                           'comedybooking'),
 ('Comedian', 'Reality Show Comedians'): ('realityshowcomedians',
                                          'indianrealityshowcomedians',
                                          'realityshowcomediansbooking',
                                          'comedyindia',
                                          'standupindia',
                                          'comedybooking'),
 ('Comedian', 'Stand Up'): ('standupcomedyindia',
                            'indianstandup',
                            'standupcomedianindia',
                            'comedyindia',
                            'standupindia',
                            'comedybooking'),
 ('DJ', 'Bass'): ('bass', 'indianbass', 'bassbooking', 'djindia', 'eventdj', 'djbooking'),
 ('DJ', 'Bollywood'): ('bollywoodsinger',
                       'bollywoodmusic',
                       'bollywoodlive',
                       'bollywoodartist',
                       'djindia',
                       'eventdj',
                       'djbooking'),
 ('DJ', 'Deep House'): ('deephouseindia',
                        'deephousedj',
                        'deephousemusicindia',
                        'djindia',
                        'eventdj',
                        'djbooking'),
 ('DJ', 'Dubstep'): ('dubstep',
                     'indiandubstep',
                     'dubstepbooking',
                     'djindia',
                     'eventdj',
                     'djbooking'),
 ('DJ', 'EDM'): ('edmindia', 'edmdj', 'electronicmusicindia', 'djindia', 'eventdj', 'djbooking'),
 ('DJ', 'Electro'): ('electro',
                     'indianelectro',
                     'electrobooking',
                     'djindia',
                     'eventdj',
                     'djbooking'),
 ('DJ', 'Fusion'): ('fusion', 'indianfusion', 'fusionbooking', 'djindia', 'eventdj', 'djbooking'),
 ('DJ', 'Indie'): ('indie', 'indianindie', 'indiebooking', 'djindia', 'eventdj', 'djbooking'),
 ('DJ', 'Minimal'): ('minimal',
                     'indianminimal',
                     'minimalbooking',
                     'djindia',
                     'eventdj',
                     'djbooking'),
 ('DJ', 'Pop'): ('pop', 'indianpop', 'popbooking', 'djindia', 'eventdj', 'djbooking'),
 ('DJ', 'Progressive'): ('progressive',
                         'indianprogressive',
                         'progressivebooking',
                         'djindia',
                         'eventdj',
                         'djbooking'),
 ('DJ', 'Psychedelic'): ('psychedelic',
                         'indianpsychedelic',
                         'psychedelicbooking',
                         'djindia',
                         'eventdj',
                         'djbooking'),
 ('DJ', 'Rock'): ('rock', 'indianrock', 'rockbooking', 'djindia', 'eventdj', 'djbooking'),
 ('DJ', 'Sufi'): ('sufi', 'indiansufi', 'sufibooking', 'djindia', 'eventdj', 'djbooking'),
 ('DJ', 'Techno'): ('techno', 'indiantechno', 'technobooking', 'djindia', 'eventdj', 'djbooking'),
 ('DJ', 'Trance'): ('trance', 'indiantrance', 'trancebooking', 'djindia', 'eventdj', 'djbooking'),
 ('DJ', 'Trap'): ('trap', 'indiantrap', 'trapbooking', 'djindia', 'eventdj', 'djbooking'),
 ('DJ', 'Virtual DJ'): ('virtualdj',
                        'indianvirtualdj',
                        'virtualdjbooking',
                        'djindia',
                        'eventdj',
                        'djbooking'),
 ('Live Band', 'Alternative'): ('alternative',
                                'indianalternative',
                                'alternativebooking',
                                'livebandindia',
                                'eventbandindia',
                                'bandbooking'),
 ('Live Band', 'Blues'): ('blues',
                          'indianblues',
                          'bluesbooking',
                          'livebandindia',
                          'eventbandindia',
                          'bandbooking'),
 ('Live Band', 'Bollywood'): ('bollywoodsinger',
                              'bollywoodmusic',
                              'bollywoodlive',
                              'bollywoodartist',
                              'livebandindia',
                              'eventbandindia',
                              'bandbooking'),
 ('Live Band', 'Electronica'): ('electronica',
                                'indianelectronica',
                                'electronicabooking',
                                'livebandindia',
                                'eventbandindia',
                                'bandbooking'),
 ('Live Band', 'Folk'): ('folk',
                         'indianfolk',
                         'folkbooking',
                         'livebandindia',
                         'eventbandindia',
                         'bandbooking'),
 ('Live Band', 'Funk'): ('funk',
                         'indianfunk',
                         'funkbooking',
                         'livebandindia',
                         'eventbandindia',
                         'bandbooking'),
 ('Live Band', 'Fusion'): ('fusion',
                           'indianfusion',
                           'fusionbooking',
                           'livebandindia',
                           'eventbandindia',
                           'bandbooking'),
 ('Live Band', 'Hip Hop'): ('hiphop',
                            'indianhiphop',
                            'hiphopbooking',
                            'livebandindia',
                            'eventbandindia',
                            'bandbooking'),
 ('Live Band', 'Indie'): ('indie',
                          'indianindie',
                          'indiebooking',
                          'livebandindia',
                          'eventbandindia',
                          'bandbooking'),
 ('Live Band', 'Jazz'): ('jazz',
                         'indianjazz',
                         'jazzbooking',
                         'jazzindia',
                         'jazzmusicianindia',
                         'livebandindia',
                         'eventbandindia',
                         'bandbooking'),
 ('Live Band', 'Metal'): ('metal',
                          'indianmetal',
                          'metalbooking',
                          'livebandindia',
                          'eventbandindia',
                          'bandbooking'),
 ('Live Band', 'Orchestra'): ('orchestra',
                              'indianorchestra',
                              'orchestrabooking',
                              'orchestraindia',
                              'orchestraperformance',
                              'livebandindia',
                              'eventbandindia',
                              'bandbooking'),
 ('Live Band', 'Pop'): ('pop',
                        'indianpop',
                        'popbooking',
                        'livebandindia',
                        'eventbandindia',
                        'bandbooking'),
 ('Live Band', 'Progressive'): ('progressive',
                                'indianprogressive',
                                'progressivebooking',
                                'livebandindia',
                                'eventbandindia',
                                'bandbooking'),
 ('Live Band', 'Psychedelic'): ('psychedelic',
                                'indianpsychedelic',
                                'psychedelicbooking',
                                'livebandindia',
                                'eventbandindia',
                                'bandbooking'),
 ('Live Band', 'Punk'): ('punk',
                         'indianpunk',
                         'punkbooking',
                         'livebandindia',
                         'eventbandindia',
                         'bandbooking'),
 ('Live Band', 'Rap'): ('rap',
                        'indianrap',
                        'rapbooking',
                        'livebandindia',
                        'eventbandindia',
                        'bandbooking'),
 ('Live Band', 'Reggae'): ('reggae',
                           'indianreggae',
                           'reggaebooking',
                           'livebandindia',
                           'eventbandindia',
                           'bandbooking'),
 ('Live Band', 'Rock'): ('rock',
                         'indianrock',
                         'rockbooking',
                         'livebandindia',
                         'eventbandindia',
                         'bandbooking'),
 ('Live Band', 'Rock N Roll'): ('rocknroll',
                                'indianrocknroll',
                                'rocknrollbooking',
                                'livebandindia',
                                'eventbandindia',
                                'bandbooking'),
 ('Live Band', 'Sufi'): ('sufi',
                         'indiansufi',
                         'sufibooking',
                         'livebandindia',
                         'eventbandindia',
                         'bandbooking'),
 ('Live Band', 'Tribute'): ('tribute',
                            'indiantribute',
                            'tributebooking',
                            'livebandindia',
                            'eventbandindia',
                            'bandbooking'),
 ('Instrumentalist', 'Flutist'): ('flutist',
                                  'indianflutist',
                                  'flutistbooking',
                                  'fluteindia',
                                  'bansuriindia',
                                  'fluteplayerindia',
                                  'instrumentalistindia',
                                  'livemusicianindia',
                                  'musicbooking'),
 ('Instrumentalist', 'Folk'): ('folk',
                               'indianfolk',
                               'folkbooking',
                               'instrumentalistindia',
                               'livemusicianindia',
                               'musicbooking'),
 ('Instrumentalist', 'Fusion'): ('fusion',
                                 'indianfusion',
                                 'fusionbooking',
                                 'instrumentalistindia',
                                 'livemusicianindia',
                                 'musicbooking'),
 ('Instrumentalist', 'Guitarist'): ('guitarist',
                                    'indianguitarist',
                                    'guitaristbooking',
                                    'guitaristindia',
                                    'acousticguitaristindia',
                                    'instrumentalistindia',
                                    'livemusicianindia',
                                    'musicbooking'),
 ('Instrumentalist', 'Indian Classical Instruments'): ('indianclassicalinstruments',
                                                       'indianindianclassicalinstruments',
                                                       'indianclassicalinstrumentsbooking',
                                                       'indianclassical',
                                                       'indianinstrumentalist',
                                                       'classicalmusicianindia',
                                                       'instrumentalistindia',
                                                       'livemusicianindia',
                                                       'musicbooking'),
 ('Instrumentalist', 'Keyboardist'): ('keyboardist',
                                      'indiankeyboardist',
                                      'keyboardistbooking',
                                      'keyboardistindia',
                                      'keyboardplayerindia',
                                      'instrumentalistindia',
                                      'livemusicianindia',
                                      'musicbooking'),
 ('Instrumentalist', 'One-Man Band'): ('onemanband',
                                       'indianonemanband',
                                       'onemanbandbooking',
                                       'instrumentalistindia',
                                       'livemusicianindia',
                                       'musicbooking'),
 ('Instrumentalist', 'Percussionist'): ('percussionist',
                                        'indianpercussionist',
                                        'percussionistbooking',
                                        'percussionistindia',
                                        'tablaartist',
                                        'instrumentalistindia',
                                        'livemusicianindia',
                                        'musicbooking'),
 ('Instrumentalist', 'Pianist'): ('pianistindia',
                                  'indianpianist',
                                  'hindipianist',
                                  'bollywoodpianist',
                                  'pianistbooking',
                                  'instrumentalistindia',
                                  'livemusicianindia',
                                  'musicbooking'),
 ('Instrumentalist', 'Saxophonist'): ('saxophonist',
                                      'indiansaxophonist',
                                      'saxophonistbooking',
                                      'saxophonistindia',
                                      'saxplayerindia',
                                      'instrumentalistindia',
                                      'livemusicianindia',
                                      'musicbooking'),
 ('Instrumentalist', 'Violinist'): ('violinist',
                                    'indianviolinist',
                                    'violinistbooking',
                                    'violinistindia',
                                    'liveviolinist',
                                    'instrumentalistindia',
                                    'livemusicianindia',
                                    'musicbooking'),
 ('Magician', 'Close Up Magicians'): ('closeupmagicians',
                                      'indiancloseupmagicians',
                                      'closeupmagiciansbooking',
                                      'magicshowindia',
                                      'eventmagician',
                                      'magicianbooking'),
 ('Magician', 'Hypnotist'): ('hypnotist',
                             'indianhypnotist',
                             'hypnotistbooking',
                             'magicshowindia',
                             'eventmagician',
                             'magicianbooking'),
 ('Magician', 'Illusionist'): ('illusionist',
                               'indianillusionist',
                               'illusionistbooking',
                               'magicshowindia',
                               'eventmagician',
                               'magicianbooking'),
 ('Magician', 'Stage Magicians'): ('stagemagicians',
                                   'indianstagemagicians',
                                   'stagemagiciansbooking',
                                   'magicshowindia',
                                   'eventmagician',
                                   'magicianbooking'),
 ('Make-up Artist / Stylist', 'Bridal & Parties'): ('bridalparties',
                                                    'indianbridalparties',
                                                    'bridalpartiesbooking',
                                                    'bridalmakeupindia',
                                                    'partymakeupindia',
                                                    'bridalartistbooking',
                                                    'makeupartistindia',
                                                    'makeupbooking'),
 ('Make-up Artist / Stylist', 'Fashion'): ('fashion',
                                           'indianfashion',
                                           'fashionbooking',
                                           'fashionstylistindia',
                                           'indianfashionstylist',
                                           'stylistbooking',
                                           'makeupartistindia',
                                           'bridalmakeupindia',
                                           'makeupbooking'),
 ('Make-up Artist / Stylist', 'Fashion Choreographer'): ('fashionchoreographer',
                                                         'indianfashionchoreographer',
                                                         'fashionchoreographerbooking',
                                                         'makeupartistindia',
                                                         'bridalmakeupindia',
                                                         'makeupbooking'),
 ('Make-up Artist / Stylist', 'Film & Television'): ('filmtelevision',
                                                     'indianfilmtelevision',
                                                     'filmtelevisionbooking',
                                                     'makeupartistindia',
                                                     'bridalmakeupindia',
                                                     'makeupbooking'),
 ('Make-up Artist / Stylist', 'Wardrobe Stylist'): ('wardrobestylist',
                                                    'indianwardrobestylist',
                                                    'wardrobestylistbooking',
                                                    'makeupartistindia',
                                                    'bridalmakeupindia',
                                                    'makeupbooking'),
 ('Singer', 'Acoustic Singer'): ('acousticsinger', 'acousticmusicindia', 'unpluggedindia'),
 ('Singer', 'Bhajan'): ('bhajansinger', 'bhajanindia', 'bhajanbooking'),
 ('Singer', 'Bollywood'): ('bollywoodsinger', 'bollywoodmusic', 'bollywoodlive', 'bollywoodartist'),
 ('Singer', 'Classical'): ('classical',
                           'indianclassical',
                           'classicalbooking',
                           'classicalsingerindia',
                           'indianclassicalsinger',
                           'hindustaniclassical'),
 ('Singer', 'English Retro'): ('englishretro', 'indianenglishretro', 'englishretrobooking'),
 ('Singer', 'Ghazal'): ('ghazalsinger', 'ghazalmusic', 'ghazalindia', 'ghazalartist'),
 ('Singer', 'Hindi Retro'): ('hindiretro', 'retrosongsindia', 'retrosinger'),
 ('Singer', 'Indian Classical'): ('indianclassicalmusic',
                                  'classicalsinger',
                                  'classicalmusicindia',
                                  'indianclassicalartist'),
 ('Singer', 'Indian Folk'): ('indianfolkmusic', 'folksingerindia', 'indianfolkartist'),
 ('Singer', 'Jagran'): ('jagran',
                        'indianjagran',
                        'jagranbooking',
                        'jagransinger',
                        'jagranmandali',
                        'jagranartist'),
 ('Singer', 'Karaoke'): ('karaoke',
                         'indiankaraoke',
                         'karaokebooking',
                         'karaokeindia',
                         'karaokesinger',
                         'karaokeartist'),
 ('Singer', 'Qawwali'): ('qawwali', 'qawwalisinger', 'qawwaliindia', 'qawwalibooking'),
 ('Singer', 'Rapper'): ('indianrapper', 'indianhiphop', 'rapmusicindia'),
 ('Singer', 'Religious'): ('religious',
                           'indianreligious',
                           'religiousbooking',
                           'devotionalmusicindia',
                           'devotionalsinger',
                           'bhajanartist'),
 ('Speaker', 'Film Stars'): ('filmstars',
                             'indianfilmstars',
                             'filmstarsbooking',
                             'speakerindia',
                             'eventspeaker',
                             'speakerbooking'),
 ('Speaker', 'Life Coach'): ('lifecoach',
                             'indianlifecoach',
                             'lifecoachbooking',
                             'speakerindia',
                             'eventspeaker',
                             'speakerbooking'),
 ('Speaker', 'Motivational'): ('motivational',
                               'indianmotivational',
                               'motivationalbooking',
                               'speakerindia',
                               'eventspeaker',
                               'speakerbooking'),
 ('Speaker', 'Spiritual'): ('spiritual',
                            'indianspiritual',
                            'spiritualbooking',
                            'speakerindia',
                            'eventspeaker',
                            'speakerbooking'),
 ('Speaker', 'Training'): ('training',
                           'indiantraining',
                           'trainingbooking',
                           'speakerindia',
                           'eventspeaker',
                           'speakerbooking'),
 ('Speaker', 'Vocational'): ('vocational',
                             'indianvocational',
                             'vocationalbooking',
                             'speakerindia',
                             'eventspeaker',
                             'speakerbooking'),
 ('Photo / Videographer', 'Baby'): ('baby',
                                    'indianbaby',
                                    'babybooking',
                                    'photographerindia',
                                    'eventphotographer',
                                    'photographybooking'),
 ('Photo / Videographer', 'Candid'): ('candid',
                                      'indiancandid',
                                      'candidbooking',
                                      'photographerindia',
                                      'eventphotographer',
                                      'photographybooking'),
 ('Photo / Videographer', 'Concept'): ('concept',
                                       'indianconcept',
                                       'conceptbooking',
                                       'photographerindia',
                                       'eventphotographer',
                                       'photographybooking'),
 ('Photo / Videographer', 'Corporate Films'): ('corporatefilms',
                                               'indiancorporatefilms',
                                               'corporatefilmsbooking',
                                               'photographerindia',
                                               'eventphotographer',
                                               'photographybooking'),
 ('Photo / Videographer', 'Documentary Films'): ('documentaryfilms',
                                                 'indiandocumentaryfilms',
                                                 'documentaryfilmsbooking',
                                                 'photographerindia',
                                                 'eventphotographer',
                                                 'photographybooking'),
 ('Photo / Videographer', 'Events'): ('events',
                                      'indianevents',
                                      'eventsbooking',
                                      'eventphotographerindia',
                                      'eventvideographerindia',
                                      'eventphotography',
                                      'photographerindia',
                                      'eventphotographer',
                                      'photographybooking'),
 ('Photo / Videographer', 'Fashion'): ('fashion',
                                       'indianfashion',
                                       'fashionbooking',
                                       'fashionstylistindia',
                                       'indianfashionstylist',
                                       'stylistbooking',
                                       'photographerindia',
                                       'eventphotographer',
                                       'photographybooking'),
 ('Photo / Videographer', 'Portfolio'): ('portfolio',
                                         'indianportfolio',
                                         'portfoliobooking',
                                         'photographerindia',
                                         'eventphotographer',
                                         'photographybooking'),
 ('Photo / Videographer', 'Portrait'): ('portrait',
                                        'indianportrait',
                                        'portraitbooking',
                                        'photographerindia',
                                        'eventphotographer',
                                        'photographybooking'),
 ('Photo / Videographer', 'Product'): ('product',
                                       'indianproduct',
                                       'productbooking',
                                       'photographerindia',
                                       'eventphotographer',
                                       'photographybooking'),
 ('Photo / Videographer', 'Short Films'): ('shortfilms',
                                           'indianshortfilms',
                                           'shortfilmsbooking',
                                           'photographerindia',
                                           'eventphotographer',
                                           'photographybooking'),
 ('Photo / Videographer', 'Weddings'): ('weddings',
                                        'indianweddings',
                                        'weddingsbooking',
                                        'weddingphotographerindia',
                                        'weddingvideographerindia',
                                        'weddingphotography',
                                        'photographerindia',
                                        'eventphotographer',
                                        'photographybooking'),
 ('Variety Artist', 'Acrobat Artists'): ('acrobatartists',
                                         'indianacrobatartists',
                                         'acrobatartistsbooking',
                                         'varietyartistindia',
                                         'evententertainmentindia',
                                         'artistbooking'),
 ('Variety Artist', 'Balloon Artists'): ('balloonartists',
                                         'indianballoonartists',
                                         'balloonartistsbooking',
                                         'varietyartistindia',
                                         'evententertainmentindia',
                                         'artistbooking'),
 ('Variety Artist', 'Bartenders'): ('bartenders',
                                    'indianbartenders',
                                    'bartendersbooking',
                                    'varietyartistindia',
                                    'evententertainmentindia',
                                    'artistbooking'),
 ('Variety Artist', 'Beatboxer'): ('beatboxer',
                                   'indianbeatboxer',
                                   'beatboxerbooking',
                                   'varietyartistindia',
                                   'evententertainmentindia',
                                   'artistbooking'),
 ('Variety Artist', 'Caricaturists'): ('caricaturists',
                                       'indiancaricaturists',
                                       'caricaturistsbooking',
                                       'varietyartistindia',
                                       'evententertainmentindia',
                                       'artistbooking'),
 ('Variety Artist', 'Fire Artists'): ('fireartists',
                                      'indianfireartists',
                                      'fireartistsbooking',
                                      'varietyartistindia',
                                      'evententertainmentindia',
                                      'artistbooking'),
 ('Variety Artist', 'Jugglers'): ('jugglers',
                                  'indianjugglers',
                                  'jugglersbooking',
                                  'varietyartistindia',
                                  'evententertainmentindia',
                                  'artistbooking'),
 ('Variety Artist', 'Mehendi Artists'): ('mehendiartists',
                                         'indianmehendiartists',
                                         'mehendiartistsbooking',
                                         'varietyartistindia',
                                         'evententertainmentindia',
                                         'artistbooking'),
 ('Variety Artist', 'Painters'): ('painters',
                                  'indianpainters',
                                  'paintersbooking',
                                  'varietyartistindia',
                                  'evententertainmentindia',
                                  'artistbooking'),
 ('Variety Artist', 'Promoters'): ('promoters',
                                   'indianpromoters',
                                   'promotersbooking',
                                   'varietyartistindia',
                                   'evententertainmentindia',
                                   'artistbooking'),
 ('Variety Artist', 'Puppeteers'): ('puppeteers',
                                    'indianpuppeteers',
                                    'puppeteersbooking',
                                    'varietyartistindia',
                                    'evententertainmentindia',
                                    'artistbooking'),
 ('Variety Artist', 'Sand Artists'): ('sandartists',
                                      'indiansandartists',
                                      'sandartistsbooking',
                                      'varietyartistindia',
                                      'evententertainmentindia',
                                      'artistbooking'),
 ('Variety Artist', 'Shadow Artists'): ('shadowartists',
                                        'indianshadowartists',
                                        'shadowartistsbooking',
                                        'varietyartistindia',
                                        'evententertainmentindia',
                                        'artistbooking'),
 ('Variety Artist', 'Stage Magicians'): ('stagemagicians',
                                         'indianstagemagicians',
                                         'stagemagiciansbooking',
                                         'varietyartistindia',
                                         'evententertainmentindia',
                                         'artistbooking'),
 ('Variety Artist', 'Stunt Artists'): ('stuntartists',
                                       'indianstuntartists',
                                       'stuntartistsbooking',
                                       'varietyartistindia',
                                       'evententertainmentindia',
                                       'artistbooking'),
 ('Influencer', 'Auto & Tech'): ('autotech',
                                 'indianautotech',
                                 'autotechbooking',
                                 'indiancreator',
                                 'brandcreatorindia',
                                 'creatorbooking'),
 ('Influencer', 'Beauty & Wellness'): ('beautywellness',
                                       'indianbeautywellness',
                                       'beautywellnessbooking',
                                       'indiancreator',
                                       'brandcreatorindia',
                                       'creatorbooking'),
 ('Influencer', 'Comedy & Humor'): ('comedyhumor',
                                    'indiancomedyhumor',
                                    'comedyhumorbooking',
                                    'indiancreator',
                                    'brandcreatorindia',
                                    'creatorbooking'),
 ('Influencer', 'Education & Learning'): ('educationlearning',
                                          'indianeducationlearning',
                                          'educationlearningbooking',
                                          'indiancreator',
                                          'brandcreatorindia',
                                          'creatorbooking'),
 ('Influencer', 'Faith & Spirituality'): ('faithspirituality',
                                          'indianfaithspirituality',
                                          'faithspiritualitybooking',
                                          'indiancreator',
                                          'brandcreatorindia',
                                          'creatorbooking'),
 ('Influencer', 'Fashion & Lifestyle'): ('fashionlifestyle',
                                         'indianfashionlifestyle',
                                         'fashionlifestylebooking',
                                         'fashioninfluencerindia',
                                         'lifestylecreatorindia',
                                         'indianfashioncreator',
                                         'indiancreator',
                                         'brandcreatorindia',
                                         'creatorbooking'),
 ('Influencer', 'Finance & Business'): ('financebusiness',
                                        'indianfinancebusiness',
                                        'financebusinessbooking',
                                        'indiancreator',
                                        'brandcreatorindia',
                                        'creatorbooking'),
 ('Influencer', 'Fitness & Health'): ('fitnesshealth',
                                      'indianfitnesshealth',
                                      'fitnesshealthbooking',
                                      'fitnessinfluencerindia',
                                      'healthcreatorindia',
                                      'indianfitnesscreator',
                                      'indiancreator',
                                      'brandcreatorindia',
                                      'creatorbooking'),
 ('Influencer', 'Food & Culinary'): ('foodculinary',
                                     'indianfoodculinary',
                                     'foodculinarybooking',
                                     'indianfoodcreator',
                                     'foodinfluencerindia',
                                     'foodbloggerindia',
                                     'indiancreator',
                                     'brandcreatorindia',
                                     'creatorbooking'),
 ('Influencer', 'Gaming & Esport'): ('gamingesport',
                                     'indiangamingesport',
                                     'gamingesportbooking',
                                     'indiancreator',
                                     'brandcreatorindia',
                                     'creatorbooking'),
 ('Influencer', 'News & Politics'): ('newspolitics',
                                     'indiannewspolitics',
                                     'newspoliticsbooking',
                                     'indiancreator',
                                     'brandcreatorindia',
                                     'creatorbooking'),
 ('Influencer', 'Pet & Animal Care'): ('petanimalcare',
                                       'indianpetanimalcare',
                                       'petanimalcarebooking',
                                       'indiancreator',
                                       'brandcreatorindia',
                                       'creatorbooking'),
 ('Influencer', 'Travel & Adventure'): ('traveladventure',
                                        'indiantraveladventure',
                                        'traveladventurebooking',
                                        'travelcreatorindia',
                                        'indiantravelinfluencer',
                                        'travelbloggerindia',
                                        'indiancreator',
                                        'brandcreatorindia',
                                        'creatorbooking'),
 ('Model', 'Art Models'): ('artmodels',
                           'indianartmodels',
                           'artmodelsbooking',
                           'indianmodel',
                           'fashionmodelindia',
                           'modelbooking'),
 ('Model', 'Catalogue Models'): ('cataloguemodels',
                                 'indiancataloguemodels',
                                 'cataloguemodelsbooking',
                                 'indianmodel',
                                 'fashionmodelindia',
                                 'modelbooking'),
 ('Model', 'Commercial Models'): ('commercialmodels',
                                  'indiancommercialmodels',
                                  'commercialmodelsbooking',
                                  'commercialmodelindia',
                                  'indiancommercialmodel',
                                  'modelbooking',
                                  'indianmodel',
                                  'fashionmodelindia'),
 ('Model', 'Foreign Models'): ('foreignmodels',
                               'indianforeignmodels',
                               'foreignmodelsbooking',
                               'indianmodel',
                               'fashionmodelindia',
                               'modelbooking'),
 ('Model', 'Glamour Models'): ('glamourmodels',
                               'indianglamourmodels',
                               'glamourmodelsbooking',
                               'indianmodel',
                               'fashionmodelindia',
                               'modelbooking'),
 ('Model', 'International Models'): ('internationalmodels',
                                     'indianinternationalmodels',
                                     'internationalmodelsbooking',
                                     'indianmodel',
                                     'fashionmodelindia',
                                     'modelbooking'),
 ('Model', 'Promotional Models'): ('promotionalmodels',
                                   'indianpromotionalmodels',
                                   'promotionalmodelsbooking',
                                   'promotionalmodelindia',
                                   'brandmodelindia',
                                   'promotionalmodelbooking',
                                   'indianmodel',
                                   'fashionmodelindia',
                                   'modelbooking'),
 ('Model', 'Runway Models'): ('runwaymodels',
                              'indianrunwaymodels',
                              'runwaymodelsbooking',
                              'runwaymodelindia',
                              'indianrunwaymodel',
                              'fashionmodelindia',
                              'indianmodel',
                              'modelbooking')}

def prompt_path(kind: str) -> Path:
    """Return the prompt template for a supported research kind."""
    if kind not in {"artist", "actor"}:
        raise ValueError("kind must be 'artist' or 'actor'")
    return PROMPTS / f"{kind}_research.md"
